### ISSUE TITLE
simultaneous port number usage?

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#100]
I'm sorry for not asking about this previously. In this text,

"Absent any coordination between the UE and the ATSSS UPF (e.g., assignment of port ranges), the same port number may be used simultaneously by the ATSSS UPF and the UE; which is problematic."

"To avoid such issue, the ATSSS UPF may be configured with a pool of IP addresses that it can use in the Internet-facing interfaces instead of preserving the MA IP address assigned to the UE. How that pool is used is deployment- and implementation-specific."

1) what's the problem, and 
2) is that relevant to IETF readers? 

If not, we can probably delete this text, but it's been in the master branch for a while ...

**Comment by boucadair** [comment]
It is relevant as this has implications on the solution design to support incoming connections.

**Comment by SpencerDawkins** [comment]
Hi, Med,

I believe you (so, relevant to IETF readers), but the text isn't clear on what the problems are. Could you suggest text that describes the issue?

**Comment by boucadair** [comment]
I guess you are referring to the problem in this text:

"Absent any coordination between the UE and the ATSSS UPF (e.g., assignment of port ranges), the same port number may be used simultaneously by the ATSSS UPF and the UE; which is problematic."

Consider the situation where: 
(1) a packet ( sent by an UE with MA IP@ and source port number =p1
(2) the ATSSS UPF translates the per-access addresses to MA IP@ and port number p1 of an outgoing packet eligible for the ATSSS service. 

When a packet is received by the UPF from Internet and destined to MA IP@ and port number p1, the UPF does not know if this a reply to (1) or (2).

I don't think that we need to add more details to the draft. The port number thing is there to explain why a dedicated pool may be used by the ATSSS UPF, while the UE is already assigned three @es.

I can add more text in the next iteration of the draft if we receive comments.

**Comment by SpencerDawkins** [comment]
Hi, Med, 

You explained the problem fairly clearly, but I didn't understand it from the text. I'd feel better if we addressed it now. 

Would you believe this text?

"Absent any coordination between the UE and the ATSSS UPF (e.g., assignment of port ranges), the same IP address and port number could be used simultaneously by the ATSSS UPF and the UE; which is problematic."

Leaving the second paragraph unchanged, as 

"To avoid such issue, the ATSSS UPF may be configured with a pool of IP addresses that it can use in the Internet-facing interfaces instead of preserving the MA IP address assigned to the UE. How that pool is used is deployment- and implementation-specific."

**Comment by boucadair** [comment]
> 
> 
> Hi, Med,
> 
> You explained the problem fairly clearly, but I didn't understand it from the text. I'd feel better if we addressed it now.
> 
> Would you believe this text?
> 
> "Absent any coordination between the UE and the ATSSS UPF (e.g., assignment of port ranges), the same IP address and port number could be used simultaneously by the ATSSS UPF and the UE; which is problematic."
> 
> Leaving the second paragraph unchanged, as
> 
> "To avoid such issue, the ATSSS UPF may be configured with a pool of IP addresses that it can use in the Internet-facing interfaces instead of preserving the MA IP address assigned to the UE. How that pool is used is deployment- and implementation-specific."

Happily. Please see #102
