### ISSUE TITLE
https://github.com/obonaventure/draft-quic-atsss-reqs/pull/93 "merged" but not in master

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#108]
I just ran the master branch through idnits and see the same complaints about references. Could you check on this?

  == Missing Reference: 'RFC8684' is mentioned on line 532, but not
     defined
'MPC: MP_CAPABLE option [RFC8684]...'

  == Unused Reference: 'I-D.schinazi-masque-protocol' is defined on line
     1034, but no explicit reference was found in the
     text
     '[I-D.schinazi-masque-protocol] Schinazi, D., "The MASQUE Protocol",...'

**Comment by boucadair** [comment]
I suggest s/RFC8684/RFC6824 for (1)

> == Unused Reference: 'I-D.schinazi-masque-protocol' is defined on line
> 1034, but no explicit reference was found in the
> text
> '[I-D.schinazi-masque-protocol] Schinazi, D., "The MASQUE Protocol",...'

Hmm, we do have this: 

895	   (1) The proposed MASQUE working group extends the HTTP/3 CONNECT
896	   method with a UDPCONNECT method to use QUIC as a tunnel for UDP
897	   traffic [I-D.schinazi-masque-connect-udp].  Another use case in scope
898	   for MASQUE is IP proxying which can be used for tunneling and
899	   forwarding of TCP connections [I-D.schinazi-masque-protocol].

**Comment by mpiraux** [comment]
I think I did remove the ref because the Makefile was warning that it was not used. We can add it back of course instead of changing for RFC6824

**Comment by boucadair** [comment]
> 
> 
> I think I did remove the ref because the Makefile was warning that it was not used. We can add it back of course instead of changing for RFC6824

It is better to cite RFC6824 as it is the one cited in the 3GPP spec. 

idnits should normally complain that we are citing RFC6824, obsoleted by RFC 8684!
