### ISSUE TITLE
Steering with QUIC connection migration

### ISSUE THREAD

**Issue by nkeukeleire** [obonaventure/draft-quic-atsss-reqs#36]
In the document, the ATSSSv2 with single QUIC connection says the following:

> In this case, there is one QUIC session between the UE and the ATSSS function. This QUIC session uses only one access network at a time. Thanks to the connection migration capability of QUIC, it is possible to support the switching function of ATSSS, but **steering** and splitting **cannot be supported.**

As the UE knows the number of available accesses and manages their usage, is it really impossible to implement some steering?

**Comment by mpiraux** [comment]
Keep in mind that there is only one QUIC session over one of the access networks. One can migrate the session over another access networks, but that switches all the flows it convey. Steering is the ability to choose an access network for a new flow. When only one session exists, there is only one choice, and thus no ability to choose per se.

**Comment by nkeukeleire** [comment]
Indeed, all flows would have to be steered on the same access. Thanks!

**Comment by nkeukeleire** [comment]
@mpiraux it seems this change still made it to the document in PR #42 :

> switching and steering functions of ATSSS, but splitting cannot be supported.
