### ISSUE TITLE
Add information for contributors

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#5]
Suggest something like 

## Venues for Contribution and Discussion

This document is in the Github repository at:

https://github.com/obonaventure/draft-quic-atsss-reqs/

Readers are welcome to open issues and send pull requests for this document.

**Comment by obonaventure** [comment]
Fine for me, if everybody agrees, I can integrate in the text

**Comment by mpiraux** [comment]
Fixed by #33
