### ISSUE TITLE
Ascii diagram showing IETF view of key ATSSS features

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#6]
One of the biggest impediments to IETF understanding of 3GPP issues is the density of 3GPP diagrams. 

We need something much simpler in this document.

**Comment by mpiraux** [comment]
I think it is important to make it a simple as possible. In that regard, using 3GPP terminology is not appropriate in my opinion. I believe we can capture the 3GPP issues with IETF language only. To me, the goal of the document is to "educate" about what's ATSSS in IETF terms, rather then introducing IETFers to ATSSS in 3GPP words. I don't expect people reading this document to read other 3GPP documents. This one should be sufficient to understand what's ATSSS, what are the requirements for ATSSS to work and why QUIC is relevant to achieve this.

**Comment by SpencerDawkins** [comment]
Maxime, I agree - does anyone not agree?
