### ISSUE TITLE
issues with single connections (Olivier)

### ISSUE THREAD

**Issue by boucadair** [obonaventure/draft-quic-atsss-reqs#68]
In #56, Olivier suggested the following limitations:

* the two QUIC connections are throttled by their congestion control scheme, which means that the available bandwidth on each will vary over time. It will be difficult for an application that manages them in real-time to schedule packets while the scheduler included inside Multipath QUIC would have access to the congestion control information

* if one of the QUIC connections is lossy, e.g. when a UE moves out of the reach of one access network, an application managing them would not be able to detect this problem unless it includes its own acknowledgements or loss measurements. Multipath QUIC includes loss detection techniques.

We need to insert those in the draft. 

I removed this one because this is covered by the use of PMF: 

* if one of the QUIC connections suffers from a much longer latency than the other, it will be difficult for an application that uses them to detect this problem without using application-level rat measurements. Multipath QUIC carries these measurements automatically.

**Comment by mpiraux** [comment]
The PR has been merged.
