### ISSUE TITLE
Meta-data cleanup

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#7]
title: ATSSS Requirements for QUIC - should not focus on "requirements", at least not at this point. 
suggest something like "3GPP Access Traffic Steering, Switching & Splitting, and Implications for IETF Transport Protocols"
abbrev: QUIC ATSSS
docname: draft-bla-quic-atsss-reqss-00 - should have a person's name where "bla" is in the draft filename
date: 2020-04-15
category: exp - should be category: info

**Comment by obonaventure** [comment]
Agreed, bla should be the one who'll have written the largest part of the text, we'll see once it converges

**Comment by SpencerDawkins** [comment]
Hi, Olivier, 

I'm fine with whatever happens with the docname, but you DID get us started ;-)

And thanks for that.

**Comment by SpencerDawkins** [comment]
Does anyone have an objection to -bonaventure- in the document file name? If not, we can update that and close this issue.

**Comment by mpiraux** [comment]
Consensus: use -bonaventure- instead of -bla-
