### ISSUE TITLE
Notes for Readers

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#75]
It would be helpful to add Notes for IETF readers, 3GPP readers, and (for extra credit) a section that says "we know we're talking about drafts that haven't been adopted by QUIC, and we know we're talking about MASQUE, that hasn't been chartered yet, but we want to reflect our understanding of what the IETF QUIC community is thinking". 

You can assign this one to me, if we're doing assignments.

**Comment by boucadair** [comment]
Hi Spencer, 

I'm not sure we need to mention MASQUE given that the MASQUE charter under IESG ballot says explicitly the following:

==
Impacts on address migration, NAT rebinding, and future multipath mechanisms of
QUIC are not anticipated. However, the working group should document these
impacts if they arise.
==

**Comment by SpencerDawkins** [comment]
Med, I believe you, but the master branch mentions the MASQUE protocol now :-) 

More seriously, that charter hasn't even gone to the IETF and other SDOs for comment, so I'm not sure I think that scope limitation is realistic, but we should absolutely agree on whether MASQUE is in or out.

**Comment by boucadair** [comment]
Agree that the draft still mention MASQUE, but I hope this will be resolved as part of #64.

We need to be consistent.
