### ISSUE TITLE
Potential Reassembly?

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#91]
From Markus, in comments on the the Gap Analysis section. 

"MP-QUIC has to consider demands from a potential re-assembly function, such as sequencing?"

Keeping in mind that https://datatracker.ietf.org/doc/html/draft-deconinck-quic-multipath-04 isn't a working group draft, so this could change, but it doesn't seem to include re-assembly (at a grep-the-draft level of inspection). 

I would expect that this would be provided at the application level (or perhaps as a shim between the application and MP-QUIC), because so many applications would not require sequencing, although I could easily be wrong. Perhaps this is better phrased as "we recognize that MP-QUIC may not provide reassembly and sequencing"?

**Comment by markusa** [comment]
Agree in principle with some small modification:

"we recognize that MP-QUIC may not provide reassembly or an appropriate sequencing to solve this protocol independent"

**Comment by SpencerDawkins** [comment]
Markus, I'll use that in the PR I have open now. Thanks.
