### ISSUE TITLE
"ATSSS Version 1" and ATSSS Version 2" isn't actually what 3GPP calls them, is it?

### ISSUE THREAD

**Issue by SpencerDawkins** [obonaventure/draft-quic-atsss-reqs#92]
I apologize for not asking this sooner, but "ATSSS Version 1" and "ATSSS Version 2" don't seem to be common terms in 3GPP. 

Would it be wrong, or jarring to the reader, if these were "ATSSS Phase 1" and "ATSSS Phase 2", which at least matches https://portal.3gpp.org/ngppapp/CreateTdoc.aspx?mode=view&contributionUid=SP-200095, or even "Release 16 ATSSS" and "Release 17 ATSSS"?

**Comment by boucadair** [comment]
"ATSSS Phase 1" and "ATSSS Phase 2" are fine by me.

**Comment by mpiraux** [comment]
The PR has been merged.
