### ISSUE TITLE
Higher vs lower layer steering

### ISSUE THREAD

**Issue by abrunstrom** [obonaventure/draft-quic-atsss-reqs#95]
We say 

> Techniques to provide ATSSS are classified by the 3GPP into two flavors: (1) high-layer techniques which operate above the IP layer (e.g., MPTCP), and (2) low-layer techniques which operate below the IP layer. Only high-layer steering techniques are discussed in this document.

But we mention transporting also IP traffic over QUIC somewhere later, so this is not consistent. 

As transporting IP is also in several of the inputs just circulated, we should perhaps avoid scoping QUIC to only higher layer steering?

**Comment by boucadair** [comment]
IMO, if we mention LL, we should not reason about IP/UDP/TCP anymore, but only L2 (Ethernet) frames. 

That's said, it is probably OK to remove "Only high-layer steering techniques are discussed in this document." 

and

s/to enable so called ATSSS higher-layer steering for all traffic/to enable ATSSS for all traffic

**Comment by mirjak** [comment]
IP over QUIC is still higher-layer as there is another IP layer underneath QUIC. So from my understanding this is correct, however, maybe we can clarify the definition. My understand of lower layer was also that this can be done by the network without impact of the UE.

**Comment by mirjak** [comment]
@boucadair as I just said I think it correct to say only higher-layer steering is discussed because there is yet another mode that we don't this discuss. However, I see how this can be confusing when we don't explain that this mode exists.

**Comment by abrunstrom** [comment]
@mirjak if that is what " operate above the IP layer" means then QUIC carrying Ethernet frames is also higher layer steering and I have no idea what QUIC-LL steering would mean? QUIC used without IP underneath? I think this is not the intention.

**Comment by boucadair** [comment]
> 
> 
> @boucadair as I just said I think it correct to say only higher-layer steering is discussed between there is yet another mode that we don't this discuss. However, I see how this can be confusing when we don't explain that this mode exists.

I agree with you, but I think that we don't lose much if we make the proposed changes.

**Comment by mirjak** [comment]
Who did bring up QUIC-LL? I think that just don't make sense...

**Comment by abrunstrom** [comment]
@boucadair I think your proposed fix would solve the issue (at least for now), then we may want to be more explicit about this in later versions.

**Comment by markusa** [comment]
> 
> 
> Who did bring up QUIC-LL? I think that just don't make sense...

A lot if inputs for the next SA2 meeting

**Comment by abrunstrom** [comment]
@mirjak several of the inputs in the list for for 3GPP that Dieter circulated. You can carry IP (or Ethernet) over QUIC and we also mention IP in the draft.

**Comment by boucadair** [comment]
> 
> 
> @mirjak several of the inputs in the list for for 3GPP that Dieter circulated. You can carry IP (or Ethernet) over QUIC and we also mention IP in the draft.

What is odd is that "IP is not above or below " IP :-)

As I said earlier, if we reason LL, we don't stay at low layers.

**Comment by boucadair** [comment]
> 
> 
> @mirjak several of the inputs in the list for for 3GPP that Dieter circulated. You can carry IP (or Ethernet) over QUIC and we also mention IP in the draft.

What is odd is that IP is not "above or below" IP as per 23501 definitions :-)

As I said earlier, if we reason LL, we need to stay at low layers.

**Comment by mirjak** [comment]
It's okay to carry IP or Ethernet over QUIC, I'm just saying I don't think this can be called a lower layer solution.

**Comment by abrunstrom** [comment]
I think you have to view it from the perspective of the traffic you serve, not from how you implement it, and then anything that carry IP or Ethernet is lower layer, and QUIC LL will make perfect sense :).

**Comment by SpencerDawkins** [comment]
Should we have a protocol stack diagram to explain this? It IS complicated if you only read the text ...

**Comment by mirjak** [comment]
Okay, I reviewed the 3GPP proposals and what the call higher or lower layer we actually call UDP or IP proxying in MASQUE. I would propose to avoid this whole terminology in this draft!
