### ISSUE TITLE
Congestion Control Issues

### ISSUE THREAD

**Issue by andrkass** [obonaventure/draft-quic-atsss-reqs#96]
Proposed text:

Many applications that are sending unreliable traffic use various congestion control algorithms to detect congestion and adjust their sending rate based on inferred end-to-end latency and loss characteristics. Examples include Adaptive Video streaming using e.g. SCREAM (CITE), or other media streaming applications that use QUIC as transport layer. When using ATSSS-LL, the per path congestion control algorithm together with the scheduler and reorder engine will have a large impact on perceived end-to-end latency and loss due to the inherent difference of the individual path characteristics. 
In addition, when deploying ATSSS and ATSSS-LL in parallel and the UE is serving both reliable and unreliable flows simultaneously, different congestion control algorithms may coexist on individual paths, which may lead to fairness issues. 

We recognize that nested congestion control mechanisms (such as
QUIC encapsulated in QUIC or SCREAM encapsulated in QUIC) and coexistence of ATSSS and ATSSS-LL have implications that require further study.

**Comment by boucadair** [comment]
Thanks. 

* Does SCREAM refer to rfc8298?
* can we remove the ATSSS-LL mention?
* s/the inherent difference/the possible difference

**Comment by abrunstrom** [comment]
Few comments: 

- QUIC is not a good example for unreliable traffic as it is reliable unless you add the datagram extension. So for the "UDP over QUIC" I think you have both unreliable and reliable traffic on top. There you may also have coexistence with MPTCP. But you anyway may share with other traffic in all cases as not all flows may use ATSSS. This is not strictly a cc in cc issue, but perhaps ok to mention.
- For the IP case you of course also may have both reliable and unreliable flows on top
- Agree to remove ATSSS-LL, not sure higher and lower layer steering would coexist...

**Comment by andrkass** [comment]
- SCREAM: Johansson, Sarker, "Self-Clocked Rate Adaptation for Multimedia", RFC8298
- Agree to remove ATSSS-LL, maybe rephrasing to "When deploying ATSSSv1 and ATSSSv2 in parallel and ..."

**Comment by SpencerDawkins** [comment]
I had listed both QUIC and RTP as examples of UDP-encapsulated protocols, but removed RTP based on a comment. Perhaps "HTTP/3 and RTP" would capture the reliable-unreliable split Anna is pointing to.

**Comment by boucadair** [comment]
> 
> 
> I had listed both QUIC and RTP as examples of UDP-encapsulated protocols, but removed RTP based on a comment. Perhaps "HTTP/3 and RTP" would capture the reliable-unreliable split Anna is pointing to.

I suggested to remove RTP  to get us out of discussion like why not use MPRTP (see draft-ietf-avtcore-mprtp) for such case, etc. 

We do already have many to defend.

**Comment by SpencerDawkins** [comment]
> > I had listed both QUIC and RTP as examples of UDP-encapsulated protocols, but removed RTP based on a comment. Perhaps "HTTP/3 and RTP" would capture the reliable-unreliable split Anna is pointing to.
> 
> I suggested to remove RTP to get us out of discussion like why not use MPRTP (see draft-ietf-avtcore-mprtp) for such case, etc.
> 
> We do already have many to defend.

I don't disagree with this, but it does seem important to address Anna's point. Perhaps 

"QUIC-encapsulated protocols, which may or may not use unreliable datagrams" 

or something like that.

**Comment by boucadair** [comment]
> QUIC-encapsulated protocols, which may or may not use unreliable datagrams

That's better. Thanks.
